package com.mycompany.barangaymanagementsystem;

import javax.swing.JOptionPane;
import javax.swing.JLabel;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JComboBox;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import javax.swing.UIManager;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.IOException;

public class Login extends javax.swing.JFrame {

    private Map<String, String> userAccounts = new HashMap<>();
    private Map<String, String> adminAccounts = new HashMap<>();

    public Login() {
        initComponents();
        loadUserAccounts();
        loadAdminAccounts();

        // Initialize the show password checkbox
        JCheckBox showPasswordCheckBox = new JCheckBox("Show");
        showPasswordCheckBox.setFont(new java.awt.Font("Arial", 1, 18));
        
        showPasswordCheckBox.setBounds(750, 610, 100, 30);
        showPasswordCheckBox.setOpaque(false);
        
        
        showPasswordCheckBox.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                if (evt.getStateChange() == ItemEvent.SELECTED) {
                    password.setEchoChar('\0');
                } else {
                    password.setEchoChar((char) UIManager.get("PasswordField.echoChar"));
                }
            }
        });

        getContentPane().add(showPasswordCheckBox);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        getContentPane().add(jLabel2);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        userType = new javax.swing.JComboBox<>();
        loginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1210, 930));
        setResizable(false);
        getContentPane().setLayout(null);

        username.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(username);
        username.setBounds(450, 480, 290, 30);

        password.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(password);
        password.setBounds(450, 610, 290, 30);

        userType.setBackground(new java.awt.Color(254, 250, 224));
        userType.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        userType.setBorder(null);
        userType.setFocusable(false);
        getContentPane().add(userType);
        userType.setBounds(1050, 40, 120, 35);

        loginButton.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonIdle.png"))); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setFocusPainted(false);
        loginButton.setIconTextGap(-130);
        loginButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(480, 775, 240, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void loadUserAccounts() {
        loadAccountsFromFile("user.txt", userAccounts);
    }

    private void loadAdminAccounts() {
        loadAccountsFromFile("admin.txt", adminAccounts);
    }
    
        private void loadAccountsFromFile(String fileName, Map<String, String> accounts) {
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new FileReader(fileName));
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(" \\|\\| ");
                if (parts.length == 2) {
                    accounts.put(parts[0], parts[1]);
                }
            }
        } catch (FileNotFoundException e) {
            System.out.println("File not found: " + fileName);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (reader != null) {
                    reader.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        }
            
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    String usernameInput = username.getText();
    String passwordInput = new String(password.getPassword());
    String selectedUserType = (String) userType.getSelectedItem();

    if (selectedUserType.equals("User")) {
        if (userAccounts.containsKey(usernameInput) && userAccounts.get(usernameInput).equals(passwordInput)) {
            JOptionPane.showMessageDialog(null, "User logged in successfully.");
            userHome userHomeFrame = new userHome();
            userHomeFrame.setWelcomeName(usernameInput); 
            userHomeFrame.setVisible(true); 
    this.dispose(); 
    } else {
    JOptionPane.showMessageDialog(null, "Invalid username or password.");
        }
    } else if (selectedUserType.equals("Admin")) { 
        if (adminAccounts.containsKey(usernameInput) && adminAccounts.get(usernameInput).equals(passwordInput)) {
            JOptionPane.showMessageDialog(null, "Admin logged in successfully.");
            Home homeFrame = new Home();
            homeFrame.setLoggedInUsername(usernameInput); 
            homeFrame.setVisible(true); 
            this.dispose(); 
            Home.setLoggedInUserPassword(passwordInput);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid admin username or password.");
        }
    }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> userType;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
